namespace: finallycoffee
name: databases
version: 0.1.4
readme: README.md
authors:
- transcaffeine <transcaffeine@finally.coffee>
description: Collection for deploying and configuring databases
dependencies:
  "community.docker": "^4.0.0"
  "community.postgresql": "^3.9.0"
  "containers.podman": "^1.16.0"
license_file: LICENSE.md
build_ignore:
- '*.tar.gz'
repository: https://git.finally.coffee/finallycoffee/databases
issues: https://codeberg.org/finallycoffee/ansible-collection-databases/issues
tags:
  - elasticsearch
  - redis
  - mariadb
  - postgresql
  - postgres
  - valkey
  - docker
