namespace: finallycoffee
name: databases
version: 0.1.0
readme: README.md
authors:
- transcaffeine <transcaffeine@finally.coffee>
description: Collection for deploying and configuring databases
dependencies:
  "community.docker": "^3.0.0"
license_file: LICENSE.md
build_ignore:
- '*.tar.gz'
repository: https://git.finally.coffee/finallycoffee/databases
issues: https://codeberg.org/finallycoffee/ansible-collection-databases/issues
tags:
  - elasticsearch
  - redis
  - mariadb
  - docker
